---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/name: {{ .Values.appName }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: {{ .Values.app.componentName }}
    app.kubernetes.io/part-of: {{ .Values.partOf }}
data:
  RAILS_ENV: "production"