apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
  labels:
    app.kubernetes.io/name: {{ .Values.appName }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: {{ .Values.app.componentName }}
    app.kubernetes.io/part-of: {{ .Values.partOf }}
spec:
  tls:
    - hosts:
        - {{ .Values.app.api_url }}
      secretName: {{ .Chart.Name | replace "." "-" }}-ktls
  rules:
    - host: {{ .Values.app.api_url }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Chart.Name }}
                port:
                  number: 3000
